carts/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import (
	cart_home, 
	cart_update,
	checkout_home,
	checkout_done_view
	)

app_name = 'products'
urlpatterns = [

	path('', cart_home, name='home'),
	# re_path(r'^(?P<slug>[\w-]+)/$', cart_update.as_view(), name='detail'),
	url(r'^checkout/success/$', checkout_done_view, name='success'),
	url(r'^checkout/$', checkout_home, name='checkout'),
	url(r'^update/$', cart_update, name='update'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

# from products.views import (
# 	ProductListView, 
# 	product_list_view, 
# 	product_detail_view, 
# 	ProductDetailView,
# 	ProductFeaturedListView,
# 	ProductFeaturedDetailView,
# 	ProductDetailSlugView
# 	)

from accounts.views import LoginView, RegisterView, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView


from .views import home_page, about_page, contact_page

urlpatterns = [
	path('', home_page, name='home'),
	path('about/', about_page, name='about'),
	path('contact/', contact_page, name='contact'),
	re_path(r'^login/$', LoginView.as_view(), name='login'),
	url(r'^checkout/address/create/$',checkout_address_create_view, name='checkout_address_create_view'),
	url(r'^checkout/address/reuse/$',checkout_address_reuse_view, name='checkout_address_reuse'),
	url(r'^register/guest/$', guest_register_view, name='guest_register'),
	path('logout/', LogoutView.as_view(), name='logout'),
	# path('cart/', cart_home, name='cart'),
	url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
	url(r'^cart/', include("carts.urls", namespace='cart')),
	url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
	url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
	url(r'^register/$', RegisterView.as_view(), name='register'),
	path('bootstrap/', TemplateView.as_view(template_name='bootstrap/exemple.html')),
	url(r'^products/', include("products.urls", namespace='products')),
	url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
	url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
	path('search/', include("search.urls", namespace='search')),
	# path('featured/', ProductFeaturedListView.as_view()),
	# re_path(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
	# path('products-fbv/', product_list_view),
	# #re_path(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
	# re_path(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
	# re_path(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import (
	ProductListView, 
	# product_list_view, 
	# product_detail_view, 
	# ProductDetailView,
	# ProductFeaturedListView,
	# ProductFeaturedDetailView,
	ProductDetailSlugView
	)

app_name = 'products'
urlpatterns = [

	path('', ProductListView.as_view(), name='list'),
	re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

templates/base/css.html
{% load static %}
 <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  
<!-- Fontawesome css  -->
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

<!-- jquery-confirm css  -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">


<!-- Custom Stripe Styling css  -->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

templates/base/forms.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button type='submit' class='btn btn-danger'>Save</button>
</form>
</div>
{% endblock %}

templates/base/js.html
{% load static %}
  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


<!-- Stripr JS -->
<script src="https://js.stripe.com/v3/"></script>

    
    <!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>


<!-- JS Render -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.6/jsrender.min.js"></script>
{% include 'base/js_templates.html' %}


<!-- Django Secure AJAX JS  -->
<script src="{% static 'js/csrf.ajax.js' %}"></script>

<!-- eCommerce Custom JS  -->
<script src="{% static 'js/ecommerce.js' %}"></script>

<!-- eCommerce Main JS  -->
<script src="{% static 'js/ecommerce.main.js' %}"></script>

templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">

	<form action="" class="payment-form" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
  <div class="form-row">
    <div id="card-element" class="form-control">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class="btn btn-primary my-3 btn-load">{{:btnTitle}}</button>
</form>

</script>
{% endverbatim %}

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %} {{ brand_name }} {% else %} CFE Ecommerce {% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %} active {% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item {% if request.path == products_list_url %} active {% endif %}">
        <a class="nav-link" href="{{ products_list_url }}" tabindex="-1" aria-disabled="true">Products</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == logout_url %} active {% endif %}">
        <a class="nav-link" href="{{ logout_url }}" tabindex="-1" aria-disabled="true">Logout</a>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == login_url %} active {% endif %}">
        <a class="nav-link" href="{{ login_url }}" tabindex="-1" aria-disabled="true">Login</a>
      </li>
       <li class="nav-item {% if request.path == register_url %} active {% endif %}">
        <a class="nav-link" href="{{ register_url }}" tabindex="-1" aria-disabled="true">Register</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
        <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items }} </span><i class="fa fa-shopping-cart" aria-hidden="true"></i> </a>
      </li>
    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</nav>