carts/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import (
	cart_home, 
	cart_update,
	checkout_home,
	checkout_done_view
	)

app_name = 'products'
urlpatterns = [

	path('', cart_home, name='home'),
	# re_path(r'^(?P<slug>[\w-]+)/$', cart_update.as_view(), name='detail'),
	url(r'^checkout/success/$', checkout_done_view, name='success'),
	url(r'^checkout/$', checkout_home, name='checkout'),
	url(r'^update/$', cart_update, name='update'),
]

search/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import (
	SearchProductView
	)

app_name = 'search'
urlpatterns = [

	url(r'^$', SearchProductView.as_view(), name='query'),
	# path('', SearchProductView.as_view(), name='list'),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Product
# Create your views here.


class SearchProductView(ListView):
	template_name = "search/view.html"

	def get_context_data(self, *args, **kwargs):
		context = super(SearchProductView, self).get_context_data(*args, **kwargs)
		query = self.request.GET.get('q')
		context['query'] =query
		#SearchQuery.objects.create(query=query)
		return context

	def get_queryset(self, *args, **kwargs):
		request = self.request
		method_dict=request.GET
		query = method_dict.get('q',None)
		if query is not None:
			return Product.objects.search(query)
		return Product.objects.none()
		#return Product.objects.filter(title__iexact='pc dell')
		'''
		__icontains = field contains this
		__iexact = fields is exactly this

		'''

search/templates/search/snippets/search-form.html
<form class="form my-2 my-lg-0 search-form" action="{% url 'search:query' %}" method="GET">
	<div class="input-group">
	    <input class="form-control" type="search" placeholder="Search" name="q" aria-label="Search" value="{{ request.GET.q }}">
	    <span class="input-group-btn">
	    	<button class="btn btn-outline-success" type="submit">Search</button>
		</span>
	</div>
 </form>